### ISSUE TITLE
Other devices 

### ISSUE THREAD

**Issue by abhigoku10** [smellslikeml/ActionAI#10]
@cclauss @smellslikeml @mayorquinmachines  Hi all thanks for opensourcing and sharing your work its really good work , i have few queries 
1. can we test the work on cpu and other embedded devices 
2. can i train my model on the opensource dataset and test it for the real time environment

**Comment by smellslikeml** [comment]
Hi @abhigoku10 
Thank you for your message!
Yes, this code is designed to run on any device with an operating system with any image data set of your choice, so long as your data is organized as described in the ```README.md```.
