### ISSUE TITLE
draw_object return None

### ISSUE THREAD

**Issue by JuniorKoukponou** [smellslikeml/ActionAI#27]
Hi,

I'm quite new on Jetson TX2. Then I have a stupid question. ;-)
I meet a TypeError while running python3 iva.py 0 on my laptop.
draw_object returns None body_dict
Any idea ?
Thanks,

Traceback (most recent call last):
File "iva.py", line 238, in
for body in pose_list:
TypeError: 'NoneType' object is not iterable

**Comment by JuniorKoukponou** [comment]
Hello,
@smellslikeml Thanks for the amazing work (y)

I have a question about your draw_object method ? Do you customize it to return something ?
If yes, can I have the piece of code please ?
Thanks
Jr

**Comment by smellslikeml** [comment]
Hi @JuniorKoukponou, thank you for your message! I've added the fix to the iva.py script, which includes the updated DrawObject class. Make sure you've followed the Jetson nano installation requirements specified in the README. There's also extra tips in the Deployment section to guide you further. 
Cheers!

**Comment by JuniorKoukponou** [comment]
> Hi @JuniorKoukponou, thank you for your message! I've added the fix to the iva.py script, which includes the updated DrawObject class. Make sure you've followed the Jetson nano installation requirements specified in the README. There's also extra tips in the Deployment section to guide you further.
> Cheers!

Thanks a lot ... @smellslikeml 
Have a great day
