### ISSUE TITLE
This model is not working properly in my flutter application.

### ISSUE THREAD

**Issue by divyanshkumaar** [smellslikeml/ActionAI#31]
I have implemented this model but it doesn't seem to work. Is it compatible with flutter?

**Comment by ankitsinghal04** [comment]
Did you figure it out? I wanted to implement this model in my flutter application as well.

**Comment by ankitsinghal04** [comment]
@smellslikeml do you know if there is any incompatibility issues with flutter?

**Comment by smellslikeml** [comment]
@divyanshkumaar @ankitsinghal04 
This code wasn't designed with Flutter in mind - you'd have to convert the models to the appropriate format. It'd be great if you could share your results with us.

**Comment by divyanshkumaar** [comment]
I converted the model file to .tflite format but the app crashes every time I click on the Button to run ActionAI. @smellslikeml  
I found this repo through this video: https://www.youtube.com/watch?v=b8xlCNzkX5w&feature=youtu.be
I used the code in this video as my base and just added models.tflite from your repo.
