### ISSUE TITLE
Install Tensorflow 2.0

### ISSUE THREAD

**Issue by ElegantLin** [smellslikeml/ActionAI#34]
Hi,

Do you know how to install tensorflow 2.0 on Jetson. I did not find it. Thanks a lot.

**Comment by trilokpadhi** [comment]
https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform-release-notes/tf-jetson-rel.html

You can check this , I have tested it and it works for me

**Comment by ElegantLin** [comment]
OK, Thanka a lot :)
