### ISSUE TITLE
Please don't waste time on this repo.

### ISSUE THREAD

**Issue by chingweihsu0809** [smellslikeml/ActionAI#57]
Please correct me if I am wrong, but it seems to me that the code is very incomplete, and there are many mistakes in the README file. I have no idea why this repo is getting so many stars.

For example, `train.py` uses a `classifier.sav` for classifying actions, which is not provided. The model definition is not provided as well so it's impossible to train from scratch either.
Also, `train_sequential.py` doesn't include a pose estimator, so it doesn't work with the `data.csv` generated by `preprocessing.py`.

One will need to modify a lot if he or she follows the instructions in README.

**Comment by smellslikeml** [comment]
If you see improvements you'd like to make, we more than welcome contributions. We have instructions on how to respectfully do so [here](https://github.com/smellslikeml/ActionAI/blob/master/CONTRIBUTING.md). 

From what you are describing as issues, it sounds like there are some clarifications we can make to the README to use this repo properly.
